version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - backend_volume:app
  frontend:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontent_volume:app
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_app_db
    ports:
      - "5432:5432"
volumes:
  frontent_volume:
  backend_volume:
