version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    container_name: chat-app-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    networks:
      - chat_app_network
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    container_name: chat-app-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    networks:
      - chat_app_network
  database:
    image: postgres:latest
    container_name: chat-app-database
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_app_db
    ports:
      - "5432:5432"
    networks:
      - chat_app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
volumes:
  node_modules_frontend:
  node_modules_backend:
networks:
  chat_app_network: