version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    container_name: chat_app_backend
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - backend_volume:/usr/src/app
    networks:
      - chat_app_network
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    container_name: chat_app_frontend
    ports:
      - "3000:3000"
    volumes:
      - frontent_volume:/usr/src/app
    networks:
      - chat_app_network
  database:
    image: postgres:latest
    container_name: chat_app_database
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_app_db
    ports:
      - "5432:5432"
    networks:
      - chat_app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  frontent_volume:
  backend_volume:
networks:
  chat_app_network:
    driver: bridge